In [3]:
import numpy
n=numpy.arange(27)
n.reshape(3,3,3)

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [2]:
import cv2
img=cv2.imread("smallgray.png",1)
img

array([[[187, 187, 187],
        [158, 158, 158],
        [104, 104, 104],
        [121, 121, 121],
        [143, 143, 143]],

       [[198, 198, 198],
        [125, 125, 125],
        [255, 255, 255],
        [255, 255, 255],
        [147, 147, 147]],

       [[209, 209, 209],
        [134, 134, 134],
        [255, 255, 255],
        [ 97,  97,  97],
        [182, 182, 182]]], dtype=uint8)

In [11]:
img[1,0:2,0:2]

array([[198, 198],
       [125, 125]], dtype=uint8)

In [15]:
img.reshape(9,5)

array([[187, 187, 187, 158, 158],
       [158, 104, 104, 104, 121],
       [121, 121, 143, 143, 143],
       [198, 198, 198, 125, 125],
       [125, 255, 255, 255, 255],
       [255, 255, 147, 147, 147],
       [209, 209, 209, 134, 134],
       [134, 255, 255, 255,  97],
       [ 97,  97, 182, 182, 182]], dtype=uint8)

In [18]:
img.reshape(9,5).T

array([[187, 158, 121, 198, 125, 255, 209, 134,  97],
       [187, 104, 121, 198, 255, 255, 209, 255,  97],
       [187, 104, 143, 198, 255, 147, 209, 255, 182],
       [158, 104, 143, 125, 255, 147, 134, 255, 182],
       [158, 121, 143, 125, 255, 147, 134,  97, 182]], dtype=uint8)